### ISSUE TITLE
Unable to add Stickied message after some time

### ISSUE THREAD

**Issue by karmirith** [Ethorbit/Discord_Sticky-Message-Bot#12] opened 2023-06-27 01:54 UTC
Whenever I try to add a stickied message after a while, the SQLite Database locks up? Is this the bot that's causing this or something else?

**Comment by Ethorbit** [comment] 2023-06-27 02:04
Just tested my bot running on Debian 11 which has been idle for a few weeks and did not run into any lockups while adding a sticky, it has also never locked up before, so I'm leaning towards that being caused by something else.

**Comment by karmirith** [comment] 2023-06-27 04:54
Do you run your bot as root, or just as your normal user?

**Comment by Ethorbit** [comment] 2023-06-27 05:06
Normal user, it should not be run as root. 
More specifically I am using the Docker container: https://hub.docker.com/r/ethorbit/discord_sticky-message-bot

**Comment by Ethorbit** [comment] 2023-07-09 11:35
Gonna close this now since it doesn't appear to be an issue specific to the bot. If you can reproduce the issue and provide more info, feel free to open it again

**Closed as completed by Ethorbit** 2023-07-09 11:35 UTC
